name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: 
  push:
    branches:
      - main

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  Explore-Gitea-Actions:
    runs-on: host
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: update toolchain
        run: rustup update
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
      - name: Build
        run: cargo build --all --release
      - run: echo "🍏 This job's status is ${{ job.status }}."

