name: Gitea Actions Demo
run-name: pbs_cmds packaging
on: 
  push:
    branches:
      - main

jobs:
  Explore-Gitea-Actions:
    runs-on: host
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: update toolchain
        run: rustup update
      - name: Compile
        run: cargo build --release
      - name: Strip
        run: strip -s target/release/pbs_cmds
      - name: Build rpm
        run: cargo generate-rpm
      - name: publish to gitea
        run: curl --user shanks:{{ PACKAGING_TOKEN }} --upload-file target/generate-rpm/pbs_cmds-*.rpm https://git.hsg.ucar.edu/shanks/pbs_cmds/shanks/rpm/upload
